[package]
name = "my_web_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
validator = { version = "0.14", features = ["derive"] }
env_logger = "0.9"
log = "0.4"




